// <auto-generated />
using System;
using BackendTemplate.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendTemplate.Infra.Data.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20210401232620_Edit_2")]
    partial class Edit_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendTemplate.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("Hash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BackendTemplate.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("BackendTemplate.Domain.Core.Entities.EntityControl", "EntityControl", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("Ativo")
                                .HasColumnType("bit")
                                .HasColumnName("Ativo");

                            b1.Property<DateTime?>("DataInativacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataInativacao");

                            b1.Property<DateTime>("DataInclusao")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("DataInclusao");

                            b1.Property<DateTime?>("DataUltimaAlteracao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataUltimaAlteracao");

                            b1.Property<int?>("UsuarioInativacaoId")
                                .HasColumnType("int")
                                .HasColumnName("UsuarioInativacao");

                            b1.Property<int>("UsuarioInclusaoId")
                                .HasColumnType("int")
                                .HasColumnName("UsuarioInclusao");

                            b1.Property<int?>("UsuarioUltimaAlteracaoId")
                                .HasColumnType("int")
                                .HasColumnName("UsuarioUltimaAlteracao");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("EntityControl");
                });
#pragma warning restore 612, 618
        }
    }
}
